//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationTechnologiesDepartmentIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public Nullable<System.Guid> AcademicianId { get; set; }
        public Nullable<System.Guid> StudentId { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string AppointmentTopic { get; set; }
        public Nullable<bool> IsRenewable { get; set; }
        public Nullable<int> AppointmentStatusId { get; set; }
    
        public virtual Academician Academician { get; set; }
        public virtual AppointmentStatus AppointmentStatus { get; set; }
        public virtual Student Student { get; set; }
    }
}
