//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationTechnologiesDepartmentIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormStatus()
        {
            this.FormProjectConsultantChangeProposals = new HashSet<FormProjectConsultantChangeProposal>();
            this.FormProjectConsultantProposals = new HashSet<FormProjectConsultantProposal>();
            this.FormProjectDeliveryCertificates = new HashSet<FormProjectDeliveryCertificate>();
            this.FormProjectSubjectChangeProposals = new HashSet<FormProjectSubjectChangeProposal>();
            this.FormProjectTitleProposals = new HashSet<FormProjectTitleProposal>();
            this.FormThesisConsultantProposals = new HashSet<FormThesisConsultantProposal>();
            this.FormThesisConcultantChangeProposals = new HashSet<FormThesisConcultantChangeProposal>();
            this.FormThesisTitleProposals = new HashSet<FormThesisTitleProposal>();
            this.FormThesisSubjectChangeProposals = new HashSet<FormThesisSubjectChangeProposal>();
            this.FormThesisConsultantAndSubjectChangeProposals = new HashSet<FormThesisConsultantAndSubjectChangeProposal>();
            this.FormThesisExtensionProposals = new HashSet<FormThesisExtensionProposal>();
            this.FormThesisAssessmentProposals = new HashSet<FormThesisAssessmentProposal>();
            this.FormThesisDeliveryCertificates = new HashSet<FormThesisDeliveryCertificate>();
            this.FormPlagiarismReports = new HashSet<FormPlagiarismReport>();
            this.FormThesisPlagiarismReports = new HashSet<FormThesisPlagiarismReport>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormProjectConsultantChangeProposal> FormProjectConsultantChangeProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormProjectConsultantProposal> FormProjectConsultantProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormProjectDeliveryCertificate> FormProjectDeliveryCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormProjectSubjectChangeProposal> FormProjectSubjectChangeProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormProjectTitleProposal> FormProjectTitleProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisConsultantProposal> FormThesisConsultantProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisConcultantChangeProposal> FormThesisConcultantChangeProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisTitleProposal> FormThesisTitleProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisSubjectChangeProposal> FormThesisSubjectChangeProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisConsultantAndSubjectChangeProposal> FormThesisConsultantAndSubjectChangeProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisExtensionProposal> FormThesisExtensionProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisAssessmentProposal> FormThesisAssessmentProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisDeliveryCertificate> FormThesisDeliveryCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormPlagiarismReport> FormPlagiarismReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisPlagiarismReport> FormThesisPlagiarismReports { get; set; }
    }
}
