//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationTechnologiesDepartmentIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormProjectConsultantChangeProposal
    {
        public int FormId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public int ProjectId { get; set; }
        public System.Guid NewAcademicianId { get; set; }
        public string NewTopic { get; set; }
        public Nullable<int> FormStatusId { get; set; }
        public Nullable<System.Guid> OldAdvisorId { get; set; }
        public string OldTopic { get; set; }
    
        public virtual Academician Academician { get; set; }
        public virtual FormStatus FormStatus { get; set; }
        public virtual GraduationProject GraduationProject { get; set; }
        public virtual Academician Academician1 { get; set; }
    }
}
