//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationTechnologiesDepartmentIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraduationProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GraduationProject()
        {
            this.FormPlagiarismReports = new HashSet<FormPlagiarismReport>();
            this.FormProjectConsultantChangeProposals = new HashSet<FormProjectConsultantChangeProposal>();
            this.FormProjectDeliveryCertificates = new HashSet<FormProjectDeliveryCertificate>();
            this.FormProjectSubjectChangeProposals = new HashSet<FormProjectSubjectChangeProposal>();
            this.FormProjectTitleProposals = new HashSet<FormProjectTitleProposal>();
        }
    
        public int ProjectId { get; set; }
        public System.Guid StudentId { get; set; }
        public System.Guid AcademicianId { get; set; }
        public string Topic { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> IsEnglish { get; set; }
        public int ProgramId { get; set; }
        public Nullable<bool> IsPlagiarised { get; set; }
    
        public virtual Academician Academician { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormPlagiarismReport> FormPlagiarismReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormProjectConsultantChangeProposal> FormProjectConsultantChangeProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormProjectDeliveryCertificate> FormProjectDeliveryCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormProjectSubjectChangeProposal> FormProjectSubjectChangeProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormProjectTitleProposal> FormProjectTitleProposals { get; set; }
        public virtual Program Program { get; set; }
        public virtual Student Student { get; set; }
    }
}
