//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationTechnologiesDepartmentIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITDepartmentDbEntities : DbContext
    {
        public ITDepartmentDbEntities()
            : base("name=ITDepartmentDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academician> Academicians { get; set; }
        public virtual DbSet<Advisor> Advisors { get; set; }
        public virtual DbSet<Campus> Campuses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<Standing> Standings { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppointmentStatus> AppointmentStatuses { get; set; }
        public virtual DbSet<FormPlagiarismReport> FormPlagiarismReports { get; set; }
        public virtual DbSet<FormProjectConsultantChangeProposal> FormProjectConsultantChangeProposals { get; set; }
        public virtual DbSet<FormProjectConsultantProposal> FormProjectConsultantProposals { get; set; }
        public virtual DbSet<FormProjectDeliveryCertificate> FormProjectDeliveryCertificates { get; set; }
        public virtual DbSet<FormProjectSubjectChangeProposal> FormProjectSubjectChangeProposals { get; set; }
        public virtual DbSet<FormProjectTitleProposal> FormProjectTitleProposals { get; set; }
        public virtual DbSet<FormStatus> FormStatuses { get; set; }
        public virtual DbSet<GraduationProject> GraduationProjects { get; set; }
        public virtual DbSet<FormThesisConcultantChangeProposal> FormThesisConcultantChangeProposals { get; set; }
        public virtual DbSet<FormThesisConsultantProposal> FormThesisConsultantProposals { get; set; }
        public virtual DbSet<FormThesisTitleProposal> FormThesisTitleProposals { get; set; }
        public virtual DbSet<FormThesisSubjectChangeProposal> FormThesisSubjectChangeProposals { get; set; }
        public virtual DbSet<FormThesisConsultantAndSubjectChangeProposal> FormThesisConsultantAndSubjectChangeProposals { get; set; }
        public virtual DbSet<FormThesisExtensionProposal> FormThesisExtensionProposals { get; set; }
        public virtual DbSet<FormThesisAssessmentProposal> FormThesisAssessmentProposals { get; set; }
        public virtual DbSet<FormThesisPlagiarismReport> FormThesisPlagiarismReports { get; set; }
        public virtual DbSet<FormThesisDeliveryCertificate> FormThesisDeliveryCertificates { get; set; }
        public virtual DbSet<MasterThes> MasterTheses { get; set; }
    }
}
