//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationTechnologiesDepartmentIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterThes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterThes()
        {
            this.FormThesisAssessmentProposals = new HashSet<FormThesisAssessmentProposal>();
            this.FormThesisConcultantChangeProposals = new HashSet<FormThesisConcultantChangeProposal>();
            this.FormThesisConsultantAndSubjectChangeProposals = new HashSet<FormThesisConsultantAndSubjectChangeProposal>();
            this.FormThesisDeliveryCertificates = new HashSet<FormThesisDeliveryCertificate>();
            this.FormThesisExtensionProposals = new HashSet<FormThesisExtensionProposal>();
            this.FormThesisPlagiarismReports = new HashSet<FormThesisPlagiarismReport>();
            this.FormThesisSubjectChangeProposals = new HashSet<FormThesisSubjectChangeProposal>();
            this.FormThesisTitleProposals = new HashSet<FormThesisTitleProposal>();
        }
    
        public int ThesisId { get; set; }
        public System.Guid StudentId { get; set; }
        public System.Guid AdvisorId { get; set; }
        public Nullable<System.Guid> CoAdvisorId { get; set; }
        public string Topic { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> IsEnglish { get; set; }
        public int ProgramId { get; set; }
        public Nullable<bool> IsPlagiarised { get; set; }
    
        public virtual Academician Academician { get; set; }
        public virtual Academician Academician1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisAssessmentProposal> FormThesisAssessmentProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisConcultantChangeProposal> FormThesisConcultantChangeProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisConsultantAndSubjectChangeProposal> FormThesisConsultantAndSubjectChangeProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisDeliveryCertificate> FormThesisDeliveryCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisExtensionProposal> FormThesisExtensionProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisPlagiarismReport> FormThesisPlagiarismReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisSubjectChangeProposal> FormThesisSubjectChangeProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormThesisTitleProposal> FormThesisTitleProposals { get; set; }
        public virtual Program Program { get; set; }
        public virtual Student Student { get; set; }
    }
}
