//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationTechnologiesDepartmentIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectId { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectMainDomain { get; set; }
        public string ProjectSubDomains { get; set; }
        public string Problem { get; set; }
        public string Solution { get; set; }
        public string ThesisStatement { get; set; }
        public Nullable<System.Guid> StudentUserId { get; set; }
        public Nullable<System.Guid> AdvisorUserId { get; set; }
        public Nullable<int> ProjectStatusId { get; set; }
        public string FeedbackMessage { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
    
        public virtual Advisor Advisor { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual Student Student { get; set; }
    }
}
